require_relative "fedibird"
require_relative "bluesky"
require_relative "tumblr"
require_relative "blogger"
require_relative "x"
require_relative "threads"
require_relative "mixi2"
require_relative "mixi"
require_relative "jotter"
# Phase 2 以降、実装したポスターをここに追記する
